# Generated by Django 4.2.11 on 2025-02-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
